CREATE OR REPLACE TRIGGER PRCS251J.TRG_TICKETS
    BEFORE INSERT OR UPDATE OF 
    TICKET_NO
    ON TICKETS FOR EACH ROW
    BEGIN
    IF INSERTING THEN
        IF :NEW.TICKET_NO IS NULL THEN
            SELECT TICKET_NO_seq.nextval
            INTO :NEW.TICKET_NO
            FROM sys.dual;
        END IF;
    END IF;
 END; 