//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STAFF_ACCOUNT> STAFF_ACCOUNT { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<STAFF_USERS> STAFF_USERS { get; set; }
        public virtual DbSet<TIMETABLE_RECORDS> TIMETABLE_RECORDS { get; set; }
    
        public virtual int VALIDATE_USER(string p_USERNAME, string p_PASSWORD, ObjectParameter r_VALUE)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VALIDATE_USER", p_USERNAMEParameter, p_PASSWORDParameter, r_VALUE);
        }
    }
}
