//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_ACCOUNT
    {
        public decimal STAFF_ID { get; set; }
        public string STAFF_ROLE { get; set; }
        public string STAFF_FORENAME { get; set; }
        public string STAFF_SURNAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string ADDRESS_LINE { get; set; }
        public string POST_CODE { get; set; }
        public string USERNAME { get; set; }
    }
}
