//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMETABLE_RECORDS
    {
        public decimal Journey_No { get; set; }
        public string Departure_Station { get; set; }
        public string Arrival_Station { get; set; }
        public System.DateTime Departure_Time { get; set; }
        public System.DateTime Arrival_Time { get; set; }
        public string Journey_Comments { get; set; }
    }
}
