CREATE OR REPLACE VIEW TIMETABLE_RECORDS ("JOURNEY_NO", "DEPARTURE_STATION", "ARRIVAL_STATION", "DEPARTURE_TIME", "ARRIVAL_TIME", "JOURNEY_COMMENTS","JOURNEY_PRICE") AS 
SELECT
JOURNEYS.journey_id AS "JOURNEY_NO",
s1.STATION_NAME AS "DEPARTURE_STATION",
s2.STATION_NAME AS "ARRIVAL_STATION",
JOURNEYS.DEPARTURE_DATE_TIME AS "DEPARTURE_TIME",
JOURNEYS.ARRIVAL_DATE_TIME AS "ARRIVAL_TIME",
JOURNEYS.JOURNEY_COMMENTS AS "JOURNEY_COMMENTS",
JOURNEYS.JOURNEY_PRICE AS "JOURNEY_PRICE"
FROM JOURNEYS
INNER JOIN STATIONS s1 ON JOURNEYS.START_LOCATION_ID = s1.STATION_ID
INNER JOIN STATIONS s2 ON JOURNEYS.END_LOCATION_ID = s2.STATION_ID;