  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRCS251J"."HISTORY_RECORDS" ("JOURNEY_NO", "DEPARTURE_STATION", "ARRIVAL_STATION", "DEPARTURE_TIME", "ARRIVAL_TIME", "JOURNEY_COMMENTS") AS 
  SELECT
EXPIRED_JOURNEYS.journey_id AS "JOURNEY_NO",
s1.STATION_NAME AS "DEPARTURE_STATION",
s2.STATION_NAME AS "ARRIVAL_STATION",
EXPIRED_JOURNEYS.DEPARTURE_DATE_TIME AS "DEPARTURE_TIME",
EXPIRED_JOURNEYS.ARRIVAL_DATE_TIME AS "ARRIVAL_TIME",
EXPIRED_JOURNEYS.JOURNEY_COMMENTS AS "JOURNEY_COMMENTS"
FROM EXPIRED_JOURNEYS
INNER JOIN STATIONS s1 ON EXPIRED_JOURNEYS.START_LOCATION_ID = s1.STATION_ID
INNER JOIN STATIONS s2 ON EXPIRED_JOURNEYS.END_LOCATION_ID = s2.STATION_ID;
