

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EXPIRED_JOURNEYS
{

    public EXPIRED_JOURNEYS()
    {

        this.EXPIRED_TICKETS = new HashSet<EXPIRED_TICKETS>();

    }


    public decimal JOURNEY_ID { get; set; }

    public decimal START_LOCATION_ID { get; set; }

    public decimal END_LOCATION_ID { get; set; }

    public System.DateTime DEPARTURE_DATE_TIME { get; set; }

    public System.DateTime ARRIVAL_DATE_TIME { get; set; }

    public string JOURNEY_COMMENTS { get; set; }

    public decimal JOURNEY_PRICE { get; set; }



    public STATION STATION { get; set; }

    public ICollection<EXPIRED_TICKETS> EXPIRED_TICKETS { get; set; }

    public STATION STATION1 { get; set; }

}

}
