CREATE TABLE PRCS251J.TICKETS
    (TICKET_NO VARCHAR2(50),
        CONSTRAINT TICKET_NO_PK
        PRIMARY KEY (TICKET_NO),
    CUSTOMER_ID NUMBER   
    CONSTRAINT FK_CUSTOMERS
    	REFERENCES CUSTOMERS(CUSTOMER_ID)
        ON DELETE CASCADE
        NOT NULL,
    JOURNEY_ID NUMBER
    CONSTRAINT FK_JOURNEYS
        REFERENCES JOURNEYS(JOURNEY_ID)
        ON DELETE CASCADE
        NOT NULL,
    PRICE NUMBER
        CONSTRAINT PRICE_NN NOT NULL
);