BEGIN 
    INSERT INTO PRCS251J.EXPIRED_JOURNEYS SELECT *
    FROM PRCS251J.JOURNEYS WHERE(JOURNEYS.ARRIVAL_DATE_TIME < SYSDATE);
    
    INSERT INTO EXPIRED_TICKETS(customer_id , journey_id , price , ticket_no )
    SELECT CUSTOMER_ID,JOURNEY_ID,PRICE,TICKET_NO
    FROM TICKETS
    WHERE TICKETS.JOURNEY_ID IN(
        SELECT JOURNEYS.JOURNEY_ID FROM PRCS251J.JOURNEYS 
        WHERE(JOURNEYS.ARRIVAL_DATE_TIME < SYSDATE)
        );
        
    DELETE FROM PRCS251J.TICKETS 
    WHERE TICKETS.JOURNEY_ID IN(
        SELECT JOURNEYS.JOURNEY_ID FROM "PRCS251J".JOURNEYS 
        WHERE(JOURNEYS.ARRIVAL_DATE_TIME < SYSDATE)
        );    
        
    DELETE FROM PRCS251J.JOURNEYS WHERE(JOURNEYS.ARRIVAL_DATE_TIME < SYSDATE);
END;
    