
  CREATE TABLE "PRCS251J"."EXPIRED_JOURNEYS" 
   (	"JOURNEY_ID" NUMBER NOT NULL ENABLE, 
	"START_LOCATION_ID" NUMBER NOT NULL ENABLE, 
	"END_LOCATION_ID" NUMBER NOT NULL ENABLE, 
	"DEPARTURE_DATE_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"ARRIVAL_DATE_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"JOURNEY_COMMENTS" VARCHAR2(255 BYTE), 
	"JOURNEY_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "EXPIRED_JOURNEYS_PK" PRIMARY KEY ("JOURNEY_ID"), 
	 CONSTRAINT "EXPIRED_JOURNEYS_FK2" FOREIGN KEY ("END_LOCATION_ID")
	  REFERENCES "PRCS251J"."STATIONS" ("STATION_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "EXPIRED_JOURNEYS_FK1" FOREIGN KEY ("START_LOCATION_ID")
	  REFERENCES "PRCS251J"."STATIONS" ("STATION_ID") ON DELETE SET NULL ENABLE
   )