
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUSTOMER
{

    public CUSTOMER()
    {

        this.TICKETS = new HashSet<TICKET>();

        this.EXPIRED_TICKETS = new HashSet<EXPIRED_TICKETS>();

    }


    public decimal CUSTOMER_ID { get; set; }

    public string CUSTOMER_FORENAME { get; set; }

    public string CUSTOMER_SURNAME { get; set; }

    public string USERNAME { get; set; }

    public string PASSWORD { get; set; }

    public System.DateTime DATE_OF_BIRTH { get; set; }

    public string POST_CODE { get; set; }

    public string ADDRESS_LINE { get; set; }



    public ICollection<TICKET> TICKETS { get; set; }

    public ICollection<EXPIRED_TICKETS> EXPIRED_TICKETS { get; set; }

}

}
