

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HISTORY_RECORDS
{

    public decimal JOURNEY_NO { get; set; }

    public string DEPARTURE_STATION { get; set; }

    public string ARRIVAL_STATION { get; set; }

    public System.DateTime DEPARTURE_TIME { get; set; }

    public System.DateTime ARRIVAL_TIME { get; set; }

    public string JOURNEY_COMMENTS { get; set; }

    public decimal JOURNEY_PRICE { get; set; }

}

}
