
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STAFF_USERS
{

    public STAFF_USERS()
    {

        this.JOURNEYS = new HashSet<JOURNEY>();

    }


    public decimal STAFF_ID { get; set; }

    public string USERNAME { get; set; }

    public string PASSWORD { get; set; }

    public ICollection<JOURNEY> JOURNEYS { get; set; }

}

}
