
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TRAIN
{

    public decimal TRAIN_ID { get; set; }

    public string TRAIN_TYPE { get; set; }

    public decimal CARRIAGE_COUNT { get; set; }

    public string TRAIN_STATUS { get; set; }

}

}
